apiVersion: batch/v1
kind: Job
metadata:
  name: spark-preprocessor
spec:
  template:
    spec:
      containers:
        - name: spark-preprocessor
          image: docker.io/library/spark-preprocessor:latest
          imagePullPolicy: Never
          env:
            - name: MINIO_ENDPOINT
              value: 'minio-service.default.svc.cluster.local:8000'
            - name: MINIO_ACCESS_KEY
              value: 'minioadmin'
            - name: MINIO_SECRET_KEY
              value: 'minioadmin'
            - name: HTTPS
              value: 'False'
      restartPolicy: Never
