apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ubuntu/mlflow:latest
          args:
            - server
            - --backend-store-uri=s3://minio/mlflow
            - --default-artifact-root=s3://minio/mlflow
            - --host=0.0.0.0
          ports:
            - containerPort: 8002
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.default.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
