apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.19.0
          args:
            - 'mlflow'
            - 'server'
            - '--backend-store-uri=sqlite:///mlflow.db'
            - '--default-artifact-root=s3://mlflow'
            - '--host=0.0.0.0'
            - '--port=8002'
          ports:
            - containerPort: 8002
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.default.svc.cluster.local:8000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
