apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort
