apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
            - --address=:8000
            - --console-address=:8001
          ports:
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: MINIO_ROOT_USER
              value: 'minioadmin'
            - name: MINIO_ROOT_PASSWORD
              value: 'minioadmin'
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}
