apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: 'http'
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: 'console'
  selector:
    app: minio
