apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      initContainers:
        - name: create-buckets
          image: quay.io/minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio http://127.0.0.1:8000 minioadmin minioadmin
              mc mb myminio/train
              mc mb myminio/preprocessed
              mc mb myminio/raw
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: root-password
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
            - --console-address=:8001 # Force the console to use port 8001
          ports:
            - containerPort: 8000 # MinIO API
            - containerPort: 8001 # MinIO Console
          env:
            - name: MINIO_ROOT_USER
              value: 'minioadmin' # Replace with your desired username
            - name: MINIO_ROOT_PASSWORD
              value: 'minioadmin' # Replace with your desired password
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}
